######################################################################
# Automatically generated by qmake (3.0) Wed Apr 29 09:35:33 2015
######################################################################

TEMPLATE = app
TARGET = autogreenbuild
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
